import type { CharacterSheet } from "./schema";

export const kaelithSheet: CharacterSheet = {
  identite: {
    nom: "Kaelith",
    race: "Elfe des bois",
    classe: "Rôdeuse",
    niveau: 5,
    historique: "Hors-la-loi",
    alignement: "Chaotique bon",
    xp: 7340,
    citation: "la brume ne me cache rien",
  },
  caracs: { for: 12, dex: 15, con: 14, int: 10, sag: 16, cha: 13 },
  saveProficiencies: { for: false, dex: true, con: true, int: false, sag: true, cha: false },
  skillProficiencies: {
    Acrobaties: false,
    Discrétion: true,
    Escamotage: false,
    Arcanes: false,
    Histoire: false,
    Investigation: true,
    Nature: false,
    Religion: false,
    Dressage: false,
    Médecine: false,
    Perception: true,
    Perspicacité: true,
    Survie: true,
    Athlétisme: false,
    Intimidation: false,
    Persuasion: false,
    Représentation: false,
    Supercherie: true,
  },
  ca: 17,
  vitesse: "10,5 m",
  initiativeBonus: 3,
  pvMax: 45,
  desDeVie: { faces: 10, total: 5, restants: 4 },
  deathSaves: { successes: 0, failures: 0 },
  inspiration: false,
  attaques: [
    { id: "a1", name: "Arc long", bonus: 7, damage: "1d8+3 perforant" },
    { id: "a2", name: "Rapière", bonus: 7, damage: "1d8+3 perforant" },
    { id: "a3", name: "Dague", bonus: 7, damage: "1d4+3 perforant" },
  ],
  sorts: {
    caracIncantation: "sag",
    connus: [
      { slug: "amitie-avec-les-animaux", level: 1 },
      { slug: "detection-de-la-magie", level: 1 },
      { slug: "detection-des-pieges", level: 1 },
      { slug: "passage-sans-trace", level: 1 },
      { slug: "brouillard-opacifiant", level: 1 },
      { slug: "emprise-sur-les-plantes", level: 1 },
      { slug: "apercon-animal", level: 2 },
      { slug: "profil-de-brouillard", level: 2 },
    ],
    emplacements: [
      { level: 1, max: 4, used: 0 },
      { level: 2, max: 2, used: 0 },
    ],
  },
  capacites: [
    {
      id: "c1",
      name: "Ennemi juré",
      description: "Dégâts supplémentaires contre un type de créature choisi.",
    },
    {
      id: "c2",
      name: "Sens aiguisés",
      description: "Perception passive 15, avantage aux tests de Perception.",
    },
    {
      id: "c3",
      name: "Faveur naturelle",
      description: "Lance 2d8 + mod SAG pour attaques contre l'ennemi juré.",
    },
    { id: "c4", name: "Vision dans le noir", description: "Voit dans le noir jusqu'à 18 m." },
    {
      id: "c5",
      name: "Pied léger (Elfe)",
      description: "Peut traverser un terrain difficile sans ralentissement.",
    },
  ],
  personnalite: {
    traits: "Je me méfie des gens trop polis. La sincérité se cache dans le silence.",
    ideaux: "La nature protège ceux qui la respectent.",
    liens: "Je protège la forêt de Valombre depuis mon enfance.",
    defauts: "Je parle peu et mal aux inconnus. La méfiance passe avant la confiance.",
  },
  languesEtMaitrises: "Commun, Elfique, Géant. Maîtrise arc long, rapière, dague, armures légères.",
  equipement: {
    bourse: { po: 45, pa: 12, pc: 8 },
    objets: [
      { name: "Arc long", qty: 1 },
      { name: "Rapière", qty: 1 },
      { name: "Dague", qty: 2 },
      { name: "Carquois", qty: 1 },
      { name: "Flèches", qty: 20 },
      { name: "Armure de cuir clouté", qty: 1 },
      { name: "Cape de voyage", qty: 1 },
      { name: "Corde de chanvre", qty: 1 },
      { name: "Outre", qty: 1 },
      { name: "Potion de soins", qty: 2 },
    ],
  },
  couleurPion: "#3B7A57",
};
